[pytest]
# 测试用例目录
testpaths = test_case
# 用例文件匹配规则
python_files = test_*.py
# 用例类匹配规则
python_classes = Test*
# 用例方法匹配规则
python_functions = test_*
# 强制 pytest 使用 utf-8 编码，防止中文变 \uXXXX
console_output_style = classic
addopts = -v --alluredir=./report/allure_raw -p no:warnings
# 标记注册（避免未注册标记警告）
markers =
    smoke: 冒烟测试用例（核心流程）
    regression: 回归测试用例（全量流程）
    user: 用户模块用例
    order: 订单模块用例



